{% set name = "kt-legacy" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kt-legacy-{{ version }}.tar.gz
  sha256: a94112e42a50e7cc3aad31f3287aa384c23555ea1432c55b5823852e09e706cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - keras-tuner

test:
  imports:
    - kerastuner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haifeng-jin/kt-legacy
  summary: Legacy import names for Keras Tuner
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Anselmoo
